image: registry.gitlab.com/wylieyyyy/cubicle:latest

stages:
  - lint
  - test
  - build

lint:
  stage: lint
  script:
    - npm install eslint eslint-config-google
    - cargo fmt --check
    - cargo clippy -- --deny warnings
    - node node_modules/eslint/bin/eslint.js 'cubicle/res/*.js' 'cubicle/res/components/*.js'

test:
  stage: test
  script:
    - cargo test --lib

build:
  stage: build
  script:
    - cargo build --target wasm32-unknown-unknown --verbose
    - wasm-bindgen --target web target/wasm32-unknown-unknown/debug/*.wasm --out-dir build/
    - cd build/ && zip -r -FS ../cubicle.xpi -- *
  artifacts:
    paths:
      - cubicle.xpi
